name: Process Daily Opens

on:
  issues:
    types: [opened]

jobs:
  process-daily-opens:
    if: contains(github.event.issue.labels.*.name, 'daily_open')
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: read
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate issue title format
      run: |
        TITLE="${{ github.event.issue.title }}"
        if [[ ! "$TITLE" =~ ^DailyOpen\ -\ [0-9]{4}-[0-9]{2}-[0-9]{2}\ - ]]; then
          echo "Error: Invalid issue title format - '$TITLE'"
          exit 1
        fi
        
        DATE=$(echo "$TITLE" | awk -F'-' '{print $2}' | xargs)
        DEVICE_ID=$(echo "$TITLE" | awk -F'-' '{print $3}' | xargs)
        
        if [[ ! "$DATE" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
          echo "Error: Invalid date format - '$DATE'"
          exit 1
        fi
        
        if [[ -z "$DEVICE_ID" ]]; then
          echo "Error: Missing device ID"
          exit 1
        fi
        
        echo "Valid issue: Date=$DATE, Device=$DEVICE_ID"
    
    - name: Process daily open
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        # 设置Git配置
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # 提取数据
        TITLE="${{ github.event.issue.title }}"
        DATE=$(echo "$TITLE" | awk -F'-' '{print $2}' | xargs)
        DEVICE_ID=$(echo "$TITLE" | awk -F'-' '{print $3}' | xargs)
        
        # 创建stats目录
        mkdir -p stats
        
        # 初始化CSV文件(如果不存在)
        if [ ! -f "stats/daily_opens.csv" ]; then
          echo "date,device_id" > stats/daily_opens.csv
        fi
        
        # 删除该设备当天的旧记录(如果有)
        grep -v "$DATE,$DEVICE_ID" stats/daily_opens.csv > temp.csv
        mv temp.csv stats/daily_opens.csv
        
        # 添加新记录
        echo "$DATE,$DEVICE_ID" >> stats/daily_opens.csv
        
        # 提交更改
        git add stats/daily_opens.csv
        git commit -m "Update daily opens for $DATE - $DEVICE_ID"
        git push
    
    - name: Close processed issue
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        curl -X PATCH \
          -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
          -d '{"state":"closed"}'
