name: Process Device Stats

on:
  issues:
    types: [opened]

jobs:
  process-device-stats:
    if: contains(github.event.issue.labels.*.name, 'device_stats')
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: read
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Process stats data
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #!/bin/bash
          set -eo pipefail

          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global --add safe.directory /github/workspace

          # Extract and validate issue data
          TITLE="${{ github.event.issue.title }}"
          BODY=$(echo '${{ toJson(github.event.issue.body) }}' | jq -r '.')

          # Validate title format
          if ! [[ "$TITLE" =~ ^DeviceStats ]]; then
            echo "::error::Invalid issue title format: $TITLE"
            exit 1
          fi

          # Parse JSON data with error handling
          parse_field() {
            local field_name="$1"
            local value
            if ! value=$(echo "$BODY" | jq -r ".${field_name}"); then
              echo "::error::Failed to parse ${field_name}"
              exit 1
            fi
            echo "$value"
          }

          DEVICE_ID=$(parse_field "device_id")
          DATE=$(parse_field "date")
          OPEN_COUNT=$(parse_field "open_count")
          REPORT_TIME=$(parse_field "report_time")
          DEVICE_MODEL=$(parse_field "device_model")
          ANDROID_VERSION=$(parse_field "android_version")
          MANUFACTURER=$(parse_field "manufacturer")
          SDK_VERSION=$(parse_field "sdk_version")
          IP_ADDRESS=$(parse_field "ip_address")
          CITY=$(parse_field "city")
          COUNTRY=$(parse_field "country")
          REGION=$(parse_field "region")

          # Validate required fields
          REQUIRED_FIELDS=("$DEVICE_ID" "$DATE" "$OPEN_COUNT")
          for field in "${REQUIRED_FIELDS[@]}"; do
            if [[ -z "$field" || "$field" == "null" ]]; then
              echo "::error::Missing required field: $field"
              exit 1
            fi
          done

          # Prepare CSV directory and file
          CSV_DIR="stats"
          CSV_FILE="${CSV_DIR}/device_stats.csv"
          mkdir -p "$CSV_DIR"

          # Create CSV header if file doesn't exist
          if [ ! -f "$CSV_FILE" ]; then
            echo "date,device_id,open_count,report_time,device_model,android_version,manufacturer,sdk_version,ip_address,city,country,region" > "$CSV_FILE"
          fi

          # Process CSV data
          TEMP_FILE=$(mktemp)
          {
            # Keep header
            head -n 1 "$CSV_FILE"
            
            # Filter out existing entry for this device (if any)
            awk -F, -v device_id="$DEVICE_ID" '
              NR > 1 && $2 != "\""device_id"\"" { print }
            ' "$CSV_FILE"
            
            # Add new record
            echo "\"$DATE\",\"$DEVICE_ID\",$OPEN_COUNT,\"$REPORT_TIME\",\"$DEVICE_MODEL\",\"$ANDROID_VERSION\",\"$MANUFACTURER\",$SDK_VERSION,\"$IP_ADDRESS\",\"$CITY\",\"$COUNTRY\",\"$REGION\""
          } > "$TEMP_FILE" && mv "$TEMP_FILE" "$CSV_FILE"

          # Commit changes
          git add "$CSV_FILE"
          if ! git diff-index --quiet HEAD --; then
            git commit -m "📊 Update stats for device $DEVICE_ID"
            git push origin HEAD:main
            echo "::notice::Stats updated for device $DEVICE_ID"
          else
            echo "::notice::No changes to commit"
          fi

      - name: Create summary
        run: |
          echo "## 📈 Device Stats Updated" >> $GITHUB_STEP_SUMMARY
          echo "- **Device ID**: $DEVICE_ID" >> $GITHUB_STEP_SUMMARY
          echo "- **Open count**: $OPEN_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "- **Device model**: $DEVICE_MODEL ($ANDROID_VERSION)" >> $GITHUB_STEP_SUMMARY
          echo "- **Location**: $CITY, $REGION, $COUNTRY" >> $GITHUB_STEP_SUMMARY
          echo "- **IP**: $IP_ADDRESS" >> $GITHUB_STEP_SUMMARY
          echo "- **Report time**: $REPORT_TIME" >> $GITHUB_STEP_SUMMARY
