name: Process Enhanced Stats

on:
  issues:
    types: [opened]

jobs:
  process-stats:
    if: contains(github.event.issue.labels.*.name, 'usage')
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: read
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Process enhanced stats
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        # 设置Git配置
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # 提取数据
        DATE=$(echo '${{ github.event.issue.title }}' | cut -d'-' -f2 | xargs)
        DEVICE_ID=$(echo '${{ github.event.issue.body }}' | grep 'Device ID:' | cut -d':' -f2 | xargs)
        IP=$(echo '${{ github.event.issue.body }}' | grep 'IP Address:' | cut -d':' -f2 | xargs)
        DURATION=$(echo '${{ github.event.issue.body }}' | grep 'Duration (minutes):' | cut -d':' -f2 | xargs)
        
        # 创建stats目录(如果不存在)
        mkdir -p stats
        
        # 初始化CSV文件(如果不存在)
        if [ ! -f "stats/enhanced_stats.csv" ]; then
          echo "date,device_id,ip_address,duration_minutes,daily_opens" > stats/enhanced_stats.csv
        fi
        
        # 计算当日打开次数(简化处理)
        DAILY_OPENS=$(grep "$DATE" stats/enhanced_stats.csv | wc -l)
        DAILY_OPENS=$((DAILY_OPENS + 1))
        
        # 追加新记录
        echo "$DATE,$DEVICE_ID,$IP,$DURATION,$DAILY_OPENS" >> stats/enhanced_stats.csv
        
        # 提交更改
        git add stats/enhanced_stats.csv
        git commit -m "Update enhanced stats for $DATE"
        git push
